MyProjectOnlineShop/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyProjectOnlineShop.Data;

namespace MyProjectOnlineShop.Areas.Admin.Controllers
{
   [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager _dataManager;

        public HomeController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(_dataManager.ProductOperations.GetAllProducts());
        }
    }
}

MyProjectOnlineShop/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MyProjectOnlineShop.Data;
using MyProjectOnlineShop.Data.Entities;
using MyProjectOnlineShop.Services;

namespace MyProjectOnlineShop.Controllers
{
    public class CatalogController : Controller
    {
        private readonly DataManager _dataManager;

        public CatalogController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }
        public IActionResult Item(Guid id)
        {
            if (id != default)
            {
                Product entity = _dataManager.ProductOperations.GetProductById(id);
                List<AdditionalPicture> pics = _dataManager.ProductOperations.GetAdditionalPictures(entity);
                ProductRatings ratings = _dataManager.ProductOperations.GetRating(entity);
                List<ProductReview> reviews = _dataManager.ProductOperations.GetReviews(entity);
                entity.AdditionalPictures = pics;
                entity.ProductRatings = ratings;
                entity.ProductReview = reviews;
                return View("Details", entity);
            }

            return RedirectToAction("Index", "Home");
        }

        
        public IActionResult SubmitRating(Guid id, int rating)
        {
            _dataManager.ProductOperations.AddRating(id, rating);
            var entity = _dataManager.ProductOperations.GetProductById(id);
            return LocalRedirect($"~/Catalog/Item/{id}");
        }

        public IActionResult AddReview(Guid id)
        {
            Product entity = _dataManager.ProductOperations.GetProductById(id);
            ViewBag.entity = entity;
            return View();
        }

        [HttpPost]
        public IActionResult AddReview(string text, string author, Guid model)
        {
            Product entity = _dataManager.ProductOperations.GetProductById(model);
            ProductReview productReview = new ProductReview() {Author = author, ProductBase = entity, ProductBaseId = entity.Id, Text = text};
            _dataManager.ProductOperations.AddReview(productReview);
            return LocalRedirect($"~/Catalog/Item/{model}");
        }

        [HttpPost]
        public IActionResult AddToCart(Guid id, int? quantity)
        {
            Product product = _dataManager.ProductOperations.GetProductById(id);
            if (quantity > product.Quantity)
            {
                quantity = product.Quantity;
            }

            if (HttpContext.Session.Get<Cart>("cart") != null)
            {
                Cart cart = HttpContext.Session.Get<Cart>("cart");
                cart.CartItems[id.ToString()] = quantity.ToString();
                HttpContext.Session.Set<Cart>("cart", cart);
            }
            else
            {
                Cart cart = new Cart() { CartItems = { [id.ToString()] = quantity.ToString() } };
                HttpContext.Session.Set<Cart>("cart", cart);
            }

            return LocalRedirect($"~/Catalog/Item/{id}");
        }
    }
}

MyProjectOnlineShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyProjectOnlineShop.Data;
using MyProjectOnlineShop.Data.Entities;
using MyProjectOnlineShop.Models;

namespace MyProjectOnlineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _db;

        public HomeController(ILogger<HomeController> logger, AppDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Products);
        }
        public IActionResult Search(string search)
        {
            IQueryable<Product> filteredProducts = _db.Products.Where(p => p.Name.ToLower().Trim().Contains(search.Trim().ToLower()));
            return View(filteredProducts);
        }
    }
}

MyProjectOnlineShop/Views/Home/Index.cshtml
@using MyProjectOnlineShop.Data.Entities
@model IQueryable<MyProjectOnlineShop.Data.Entities.Product>
@{
    ViewData["Title"] = "My Shop | Main";
}
<div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">
        @if (Model?.Any() == true)
        {
            @foreach (Product product in Model)
            {
                <div class="single-products-catagory clearfix">
                    <a asp-controller="Catalog" asp-action="Item" asp-route-id="@product.Id">
                        <img src="/img/product-img/@product.ImgPath" alt="">
                        <div class="hover-content">
                            <div class="line"></div>
                            <p>$@product.Price</p>
                            <h4>@product.Name</h4>
                        </div>
                    </a>
                </div>
            }
        }
        else
        {
            <h2>There is no products yet, come back later!</h2>
        }
    </div>
</div>

MyProjectOnlineShop/Views/Home/Search.cshtml
@using MyProjectOnlineShop.Data.Entities
@model IQueryable<MyProjectOnlineShop.Data.Entities.Product>

@{
    ViewData["Title"] = "MyShop | Search";
}

<div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">
        @if (Model?.Any() == true)
        {
            @foreach (Product product in Model)
            {
                <div class="single-products-catagory clearfix">
                    <a asp-controller="Catalog" asp-action="Item" asp-route-id="@product.Id">
                        <img src="/img/product-img/@product.ImgPath" alt="">
                        <div class="hover-content">
                            <div class="line"></div>
                            <p>$@product.Price</p>
                            <h4>@product.Name</h4>
                        </div>
                    </a>
                </div>
            }
        }
        else
        {
            <h2>No products matching your search query.</h2>
        }
    </div>
</div>