MyProjectOnlineShop/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyProjectOnlineShop.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string Login { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

    }
}

MyProjectOnlineShop/Controllers/SigninController.cs
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyProjectOnlineShop.Models;
using System.Threading.Tasks;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace MyProjectOnlineShop.Controllers
{
    [Authorize]
    public class SigninController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public SigninController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string url)
        {
            ViewBag.url = url;
            return View(new LoginViewModel());
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginModel)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByNameAsync(loginModel.Login);
                if (user != null)
                {
                    await _signInManager.SignOutAsync();
                    SignInResult result = await _signInManager.PasswordSignInAsync(user, loginModel.Password, false, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("index", "home", new { area = "Admin" });
                    }
                }

            }
            return View(loginModel);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

MyProjectOnlineShop/Views/Signin/Login.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "My Shop | Login";
}

<link rel="stylesheet" type="text/css" href="/login/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<link rel="stylesheet" type="text/css" href="/login/vendor/animate/animate.css">
<link rel="stylesheet" type="text/css" href="/login/vendor/css-hamburgers/hamburgers.min.css">
<link rel="stylesheet" type="text/css" href="/login/vendor/animsition/css/animsition.min.css">
<link rel="stylesheet" type="text/css" href="/login/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="/login/vendor/daterangepicker/daterangepicker.css">
<link rel="stylesheet" type="text/css" href="/login/css/util.css">
<link rel="stylesheet" type="text/css" href="/login/css/main.css">

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-50 p-b-90">
            <form class="login100-form validate-form flex-sb flex-w" asp-area="" asp-controller="Signin" asp-action="Login" method="post" asp-route-url="@ViewBag.url">
                <span class="login100-form-title p-b-51">
                    Login
                </span>
                <div asp-validation-summary="All"></div>
                <div class="wrap-input100 validate-input m-b-16">
                    <label asp-for="Login"></label>
                    <input asp-for="Login" class="input100" placeholder="Username" />
                    <span asp-validation-for="Login" class="focus-input100"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-16">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="input100" placeholder="Password" />
                    <span asp-validation-for="Password" class="focus-input100"></span>
                </div>

                <div class="container-login100-form-btn m-t-17">

                    <input class="login100-form-btn" type="submit" value="ОК" />
                </div>

            </form>
        </div>
    </div>
</div>

<script src="/login/vendor/jquery/jquery-3.2.1.min.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")
<script src="/login/vendor/animsition/js/animsition.min.js"></script>
<script src="/login/vendor/bootstrap/js/popper.js"></script>
<script src="/login/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="/login/vendor/select2/select2.min.js"></script>
<script src="/login/vendor/daterangepicker/moment.min.js"></script>
<script src="/login/vendor/daterangepicker/daterangepicker.js"></script>
<script src="/login/vendor/countdowntime/countdowntime.js"></script>
<script src="/login/js/main.js"></script>